[build-system]
requires = ['setuptools>=42']
build-backend = 'setuptools.build_meta'

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = ''