name: On create pull request to develop

on:
  pull_request:
    types: [opened]
    branches: [master]

jobs:
  check_build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install pytest
          pip install pytest-cov
          pip install bandit
          pip install black
          pip install lizard
          pip install pylint
          pip install pyroma
          pip install vulture
      - name: Run security checker
        run: |
          python3 tools/checkers/bandit_run.py
      - name: Run code formater
        run: |
          python3 tools/checkers/black_run.py
      - name: Run dead code checker
        run: |
          python3 tools/checkers/vulture_run.py
      - name: Run cyclomatix complexity analyzer
        run: |
          python3 tools/checkers/lizard_run.py
      - name: Run linter
        run: |
          python3 tools/checkers/pylint_run.py
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python3 build/build.py
      - name: Install package from binary
        run: >-
          python3 tools/install.py
      - name: Run unit tests against installed package
        run: >-
          python3 tests/unit_tests/unit_tests_run.py   
      - name: Run integration tests against installed package
        run: >-
          python3 tests/integration_tests/integration_tests_run.py
      - name: Run pyroma to check package standards
        run: |
          python3 tools/checkers/pyroma_run.py