name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install pytest
          pip install bandit
          pip install black
          pip install lizard
          pip install pylint
          pip install pyroma
          pip install vulture
      - name: Run security checker
        run: |
          python3 tools/bandit_run.py
      - name: Run code formater
        run: |
          python3 tools/black_run.py
      - name: Run dead code checker
        run: |
          python3 tools/vulture_run.py
      - name: Run dead code checker
        run: |
          python3 tools/vulture_run.py
      - name: Run cyclomatix complexity analyzer
        run: |
          python3 tools/lizard_run.py
      - name: Run linter
        run: |
          python3 tools/pylint_run.py
      - name: Build package
        run: python -m build
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}      